# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='zip_code',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
