# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0002_auto_20170206_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_picture',
        ),
    ]
