# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0003_remove_student_student_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor_picture',
        ),
    ]
