# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0005_auto_20170206_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='student_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
