# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0006_auto_20170206_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_picture',
            field=models.FileField(default='default2.jpg', null=True, upload_to=''),
        ),
    ]
