# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0007_auto_20170206_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_picture',
            field=models.FileField(blank=True, default='default2.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_picture',
            field=models.FileField(blank=True, default='default2.jpg', null=True, upload_to=''),
        ),
    ]
