# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0008_auto_20170206_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='class_alt_id',
            field=models.CharField(default='no lesson id', max_length=50, null=True),
        ),
    ]
