# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0009_auto_20170206_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_alt_id',
            field=models.CharField(default='no instructor id', max_length=50, null=True),
        ),
    ]
