# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplace', '0010_auto_20170225_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room_location',
            field=models.CharField(blank=True, default='TBA', max_length=30, null=True),
        ),
    ]
