# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeclassenroll',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bridgeinstructorenroll',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
