# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0002_auto_20161227_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_description',
            field=models.CharField(max_length=500),
        ),
    ]
